### ISSUE TITLE
Ao remover o token é necessária a reexecução do componente .exe

### ISSUE THREAD

**Issue by Markenson** [assijus/assijusexe#1]
Reportado por @andresousa17 que após usar o assijus, remover o token (e mantê-lo fora por um período) o sistema não reconhece mais o token.

O @andresousa17 conseguiu fazer a aplicação funcionar realizando os procedimentos abaixo, porém está sendo necessário repeti-lo a cada vez que o problema ocorre.

1. Clicar com o botão direito do mouse no ícone do assijus e clicar em "exit"
2. Dar um refresh na página do assijus para que seja exibido o link de download do componente
3. Reinstalar o componente

**Comment by Markenson** [comment]
Reiniciar o serviço "Propagação de Certificado" resolve o problema. Uma alternativa seria reiniciar esse serviço pelo menos uma vez caso o certificado não fosse encontrado.

**Comment by Markenson** [comment]
O branch restart-svc foi criado com o código (e539bca587f28bdf76af54dea7dfa0b3857fd934) que reinicia o serviço de propagação de certificados. Isso intruduz uma confirmação do usuário (UAC) antes da execução do aplicativo.

**Comment by crivano** [comment]
Conversei com @Markenson e acreditamos que o ideal é que o executável não necessite de privilégios de administrador para rodar. Uma alternativa é indicar que é necessário resetar a máquina, quando detectarmos esse bug do windows/driver.

**Comment by crivano** [comment]
Troquei para essa mensagem aqui:

![captura_de_tela_062016_041533_pm](https://cloud.githubusercontent.com/assets/4137623/16207193/384fd91e-3702-11e6-8ff4-f114fbd489ac.jpg)

**Comment by crivano** [comment]
@Markenson , fiz uma certa confusão. Agora a imagem acima está correta! :)
