### ISSUE TITLE
Feailure opening selector ao recarregar a página após execução do Assijus.exe

### ISSUE THREAD

**Issue by Markenson** [assijus/assijusexe#2]
Ao executar o assijus.exe e, em seguida, atualizar a página no navegador, ocorreu o erro abaixo

![image](https://cloud.githubusercontent.com/assets/2985140/15971718/09e3050e-2f11-11e6-9fbd-74fcef5444ba.png)

**Comment by crivano** [comment]
@Markenson , esse é um erro decorrente do problema com o Unirest, que já foi resolvido lá.
